name: changelogs

on:
  push:
    branches:
      - '**'

jobs:
  update_changelogs:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Installing Homebrew
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
        brew --version

    - name: Install git-chglog
      run: |
        brew tap git-chglog/git-chglog
        brew install git-chglog

    - name: Install git-version
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Install pandoc
      run: brew install pandoc

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Tag the commit
      run: |
        echo "Version: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        git tag ${{ steps.gitversion.outputs.MajorMinorPatch }}

    - name: Get Changelog
      id: changelogs
      run: |
        git-chglog -o temp.md $(git describe --tags $(git rev-list --tags --max-count=1))
        pandoc temp.md -f markdown_strict -t rst -o temp.rst
        echo "" >> temp.rst
        cat temp.rst CHANGELOG.rst > tmp && mv tmp CHANGELOG.rst

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.MajorMinorPatch }}
        release_name: Release ${{ steps.gitversion.outputs.MajorMinorPatch }}
        body_path: temp.md
        draft: false
        prerelease: false

    - name: delete temp files
      run: |
        rm temp.md
        rm temp.rst

    - name: create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'docs: Bump the Version and update Changelogs'
        branch: update-changelogs
        title: Upgrade the version
