name: changelogs

on:
  push:
    branches:
      - '**'

jobs:
  update_changelogs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Installing Homebrew
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
        brew --version
    - name: Install git-chglog
      run: |
        brew tap git-chglog/git-chglog
        brew install git-chglog
    - name: Install git-version
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Tag the commit
      run: |
        echo "Version: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        git tag ${{ steps.gitversion.outputs.MajorMinorPatch }}
    - name: Get Changelog
      run: git-chglog $(git describe --tags $(git rev-list --tags --max-count=1)) -o CHANGELOG.md
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.gitversion.outputs.MajorMinorPatch }}
        release_name: Release ${{ steps.gitversion.outputs.MajorMinorPatch }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
    - name: create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'docs: Bump the Version and update Changelogs'
        branch: update-changelogs
        title: Upgrade the version
