name: changelogs

on:
  push:
    branches:
      - '**'

jobs:
  update_changelogs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Installing Homebrew
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
        brew --version
    - name: Install git-chglog
      run: |
        brew tap git-chglog/git-chglog
        brew install git-chglog
    - name: Install git-version
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Tag the commit
      run: |
        echo "Version: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        git tag ${{ steps.gitversion.outputs.MajorMinorPatch }}
    - name: Get Changelog
      run: git-chglog -o CHANGELOG.md
    - name: create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
        GITHUB_USER_EMAIL: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      run: |
        cd $GITHUB_WORKSPACE/testeng-ci
        python -m jenkins.pull_request_creator --repo-root=$GITHUB_WORKSPACE \
        --target-branch="${{ env.target_branch }}" --base-branch-name="Update Changelogs" \
        --commit-message="Updating Changelogs for next version" --pr-title="Changelogs Update" \
        --pr-body="Bump the version and update changelogs" \
        --user-reviewers="" --team-reviewers="arbi-bom" --delete-old-pull-requests