name: changelogs

on:
  push:
    branches:
      - '**'

jobs:
  update_changelogs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing Homebrew
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        echo "::add-path::/home/linuxbrew/.linuxbrew/bin"
        brew --version
    - name: Install git-chglog
      run: |
        brew tap git-chglog/git-chglog
        brew install git-chglog
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Get Version
      id: gitversion
      run: |
        GitVersion /showvariable MajorMinorPatch
    - name: Tag the commit
      run: |
        echo "Version: ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        git tag ${{ steps.gitversion.outputs.MajorMinorPatch }}
    - name: Get Changelog
      run: git-chglog